# Generated by Django 4.1.13 on 2026-02-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFT_meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together={('match', 'player')},
        ),
    ]
