# Generated by Django 4.1.13 on 2026-02-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(max_length=100, unique=True)),
                ('game_datetime', models.DateTimeField()),
                ('set_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('summoner_name', models.CharField(max_length=50)),
                ('tier', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField()),
                ('level', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFT_meta.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFT_meta.player')),
            ],
        ),
        migrations.CreateModel(
            name='DeckComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('items', models.JSONField()),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFT_meta.placement')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFT_meta.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('top4_count', models.IntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFT_meta.unit')),
            ],
            options={
                'unique_together': {('unit', 'item_id')},
            },
        ),
    ]
